### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by SebastianBehrens** [mvanderkamp/worklist.vim#2] opened 2023-08-04 22:47 UTC
Hi there, nice plugin.
I get the attached errors on Vim 9.0.
On entering (via :WorklistShow) on non-first times. (The error does not occur on the first :WorklistShow after vim startup.)
![image](https://github.com/mvanderkamp/worklist.vim/assets/51058351/2c993df9-3fbd-4a76-b4e2-cfd57644fb88)
On closing using ZZ or :q. Even when closing the buffer from the first invocation of :WorklistShow.
![image](https://github.com/mvanderkamp/worklist.vim/assets/51058351/3dd1e604-697f-4441-8842-341af85eff72)

**Comment by SebastianBehrens** [comment] 2023-08-04 22:59
I could fix the first one by setting a path for `g:worklist_dir` in `vimfiles\`, since I am on windows. But the second issue persists. As there is not BufWinLeave code in your worklist.vim file though, I suppose the error is caused by some other plugin on the quickfix buffer.

**Comment by mvanderkamp** [comment] 2023-08-05 16:59
Ahhh if you're on windows perhaps the issue is that I hardcoded the `/` slash in the `g:worklist_dir` default.

**Comment by mvanderkamp** [comment] 2023-08-05 17:06
Oh wait no I see- the issue is that I assumed `~/.vim` was a valid directory

**Comment by mvanderkamp** [comment] 2023-09-24 21:51
Addressed by #3

**Closed as completed by mvanderkamp** 2023-09-24 21:51 UTC
